### ISSUE TITLE
Adding multilingual support

### ISSUE THREAD

**Issue by lex111** [doctrine/doctrine-website-sculpin#6]
Is it possible to add translation support? For example, to translate documentation into another language? That would be great.

**Comment by Ocramius** [comment]
We don't have the throughput nor enough dedicated maintainers to follow translations closely. If we can get dedicated people that can really throw in massive amounts of time just to do the translations (long-term), then sure, but otherwise not really worth doing for now, as it's a huge huge task that takes a lot of time over the years (and not just initially).

Out of sync docs is worse than no docs in a i18n-friendly format, and our docs are already often out of sync with the sources.

**Comment by lex111** [comment]
Okay, can I create an unofficial translation using this generator?
I want to try to create a translation as part of the Doctrine study.

**Comment by jwage** [comment]
Would it be worth it to automatically generate translated versions at build time with Google? Not sure if it makes sense. People can just do that in their browser.

**Comment by jwage** [comment]
@lex111 feel free to do whatever you like with this repository. I would be interested to see what you build either way. Thanks!
